// Generated by tools/embed_ui.ps1 from merope/src/web/ui.html - do not edit.
#include "ui_assets.h"

#include <string>

// The document is held in pieces purely because MSVC caps a single string
// literal at 16 KB. They are joined once, on first use.
static constexpr std::string_view k_parts[] = {
R"MEROPE_UI(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>merope</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath d='M16 1C17.7 10.4 21.6 14.3 31 16 21.6 17.7 17.7 21.6 16 31 14.3 21.6 10.4 17.7 1 16 10.4 14.3 14.3 10.4 16 1Z' fill='%23a78bfa'/%3E%3C/svg%3E">
<style>
:root{
  --void:#04040a; --panel:#0a0a14; --panel-2:#0f0f1e; --raise:#15152a;
  --line:rgba(126,110,255,.16); --line-soft:rgba(126,110,255,.08);
  --ink:#e9e9f6; --ink-2:#9c9cbe; --ink-3:#5f5f7c;
  --violet:#8b5cf6; --indigo:#6366f1; --blue:#4f7cff; --sky:#38bdf8;
  --ok:#5eead4; --warn:#fbbf24; --stop:#fb7185;
  --mono:"Cascadia Mono","Cascadia Code",Consolas,"SF Mono",ui-monospace,monospace;
  --sans:"Segoe UI Variable Text","Segoe UI",system-ui,-apple-system,sans-serif;
  --r:10px;
}
*{box-sizing:border-box}
html,body{height:100%}
body{
  margin:0; background:var(--void); color:var(--ink);
  font-family:var(--sans); font-size:14px; line-height:1.5;
  -webkit-font-smoothing:antialiased;
}
/* Ambient field: two slow violet/blue pools over black. Set once, never moves
   fast enough to compete with the content. */
body::before{
  content:""; position:fixed; inset:-20%; z-index:0; pointer-events:none;
  background:
    radial-gradient(38% 30% at 18% 12%, rgba(99,102,241,.20), transparent 70%),
    radial-gradient(34% 34% at 84% 78%, rgba(139,92,246,.16), transparent 72%),
    radial-gradient(50% 40% at 50% 110%, rgba(79,124,255,.10), transparent 70%);
  filter:blur(6px); animation:drift 34s ease-in-out infinite alternate;
}
@keyframes drift{ to{ transform:translate3d(0,-3%,0) scale(1.06) } }

/* The Pleiades. merope is one of the seven sisters, so the cluster is the
   background: real J2000 positions projected to a plane, scaled uniformly so
   the shape stays true, with apparent magnitude driving size and brightness. */
#sky{
  position:fixed; inset:0; width:100%; height:100%;
  z-index:0; pointer-events:none; overflow:visible; opacity:.95;
}
#sky .field,
#sky .core{fill:#fff}
#sky .spike{stroke:#fff; stroke-linecap:round; opacity:.42}
#sky .name{
  fill:rgba(196,181,253,.55); font-family:var(--mono);
  font-size:1.15px; letter-spacing:.22px;
}
#sky .twinkle{animation:twinkle 5s ease-in-out infinite}
@keyframes twinkle{ 0%,100%{opacity:1} 50%{opacity:.3} }
/* The only thing up there that is not a star. One is drawn when it is due and
   removed when it lands, so nothing accumulates over a long session. */
#sky .meteor{animation:meteor 1.2s ease-in forwards}
@keyframes meteor{
  0%{opacity:0; transform:translate(4px,-2.2px)}
  14%{opacity:1}
  100%{opacity:0; transform:translate(-15px,8.3px)}
}
/* The nebula does not shine, it reflects Merope. So let it breathe, slowly. */
#sky .neb{animation:breathe 21s ease-in-out infinite}
@keyframes breathe{ 50%{opacity:.58} }

a{color:var(--sky)}
button,input,select,textarea{font:inherit;color:inherit}
:focus-visible{outline:2px solid var(--sky); outline-offset:2px; border-radius:4px}
.mono{font-family:var(--mono)}

/* ---------------------------------------------------------------- boot ---- */
/* No background of its own: the sky behind it is the point. */
#boot{
  position:fixed; inset:0; z-index:100;
  display:grid; place-items:center; gap:0;
  transition:opacity .7s ease, visibility .7s;
}
#boot.done{opacity:0; visibility:hidden}
#boot::after{
  content:""; position:absolute; inset:0; pointer-events:none;
  background:radial-gradient(46% 38% at 50% 46%, rgba(109,94,255,.22), transparent 70%);
}
.boot-inner{position:relative; z-index:1; display:grid; justify-items:center; gap:34px}

.wordmark{
  display:flex; align-items:center; gap:.012em;
  font-family:var(--sans); font-weight:200; letter-spacing:.02em;
  font-size:clamp(46px,9vw,104px); line-height:1; user-select:none;
}
/* Each letter is drawn first as horizontal scan lines, then fills in band by
   band. The stagger is what makes it read as loading rather than fading. */
.g{
  position:relative; display:inline-block; color:transparent;
  background-image:repeating-linear-gradient(to bottom,#fff 0 2px,rgba(255,255,255,0) 2px 7px);
  -webkit-background-clip:text; background-clip:text;
  animation:scan 2.6s linear infinite;
}
.g::after{
  content:attr(data-ch); position:absolute; left:0; top:0; color:#fff;
  clip-path:inset(100% 0 0 0);
  animation:fill 1.15s steps(9,end) forwards;
  animation-delay:calc(var(--i) * .24s + .45s);
}
@keyframes scan{ to{ background-position-y:7px } }
@keyframes fill{ to{ clip-path:inset(0 0 0 0) } }

/* The o is the loading ring: it spins while work is outstanding and its arc
   length is the actual boot progress. */
.ring{
  /* Sized and dropped to sit on the baseline at the x-height, so it reads as
     the lowercase o of the word and not as a badge next to it. */
  width:.54em; height:.54em; display:block; margin:0 .055em;
  transform:translateY(.105em); overflow:visible;
}
.ring .track{fill:none; stroke:rgba(255,255,255,.15); stroke-width:9}
.ring .arc{
  fill:none; stroke:url(#ringGrad); stroke-width:9; stroke-linecap:round;
  transform-origin:50% 50%; animation:spin 1.15s linear infinite;
  transition:stroke-dashoffset .5s ease;
}
@keyframes spin{ to{ transform:rotate(360deg) } }

.boot-meta{display:grid; justify-items:center; gap:14px; width:min(420px,72vw)}
.boot-rule{position:relative; width:100%; height:1px; background:rgba(255,255,255,.10)}
.boot-rule i{
  position:absolute; inset:0 auto 0 0; display:block; width:0%;
  background:linear-gradient(90deg,var(--violet),var(--blue));
  transition:width .5s ease;
}
.boot-status{
  font-family:var(--mono); font-size:11.5px; letter-spacing:.10em;
  text-transform:uppercase; color:rgba(255,255,255,.42);
}
.boot-status.bad{color:var(--stop)}

/* ------------------------------------------------------------- chrome ---- */
#app{position:relative; z-index:1; min-height:100%; display:flex; flex-direction:column}
.topbar{
  display:flex; align-items:center; gap:18px; padding:14px 22px;
  border-bottom:1px solid var(--line); background:rgba(6,6,14,.72);
  backdrop-filter:blur(14px); position:sticky; top:0; z-index:20;
}
.brand{display:flex; align-items:center; font-size:19px; font-weight:250; letter-spacing:.03em}
.brand .ring{width:.5em; height:.5em; transform:translateY(.1em)}
.brand .ring .arc{animation:none; stroke:var(--violet)}
.brand.busy .ring .arc{animation:spin 1s linear infinite}
.crumb{
  font-family:var(--mono); font-size:12px; color:var(--ink-2);
  display:flex; align-items:center; gap:10px; min-width:0;
}
.crumb b{color:var(--ink); font-weight:500; overflow:hidden; text-overflow:ellipsis; white-space:nowrap}
.crumb .sep{color:var(--ink-3)}
.spacer{flex:1}
.tag{
  font-family:var(--mono); font-size:10.5px; letter-spacing:.12em; text-transform:uppercase;
  padding:4px 9px; border:1px solid var(--line); border-radius:999px; color:var(--ink-2);
}
.tag.live{color:var(--ok); border-color:rgba(94,234,212,.28)}
.tag.dead{color:var(--stop); border-color:rgba(251,113,133,.34)}

/* The kill button ends the process that serves this page, so it does not wear
   the same colour as Run and it does not act on the first click. */
.killwrap{position:relative}
.btn.kill{
  display:flex; align-items:center; gap:8px; padding:7px 13px; font-size:12.5px; font-weight:400;
  background:none; border-color:rgba(251,113,133,.30); color:var(--ink-2);
}
.btn.kill:hover:not(:disabled){border-color:rgba(251,113,133,.62); color:var(--stop); filter:none}
.btn.kill svg{width:13px; height:13px; fill:none; stroke:currentColor; stroke-width:2.1; stroke-linecap:round}
.btn.danger{background:linear-gradient(135deg,#f43f5e,#b91c4b)}
.killpop{
  position:absolute; right:0; top:calc(100% + 10px); width:min(340px,86vw); z-index:30;
  background:var(--raise); border:1px solid rgba(251,113,133,.34); border-radius:var(--r);
  padding:15px 16px; box-shadow:0 18px 46px rgba(0,0,0,.66); animation:rise .16s ease both;
}
.killpop b{display:block; margin-bottom:6px; font-weight:500}
.killpop p{margin:0 0 13px; font-size:12.5px; color:var(--ink-2)}
.killpop code{font-family:var(--mono); font-size:11.5px; color:var(--ink)}
.killrow{display:flex; gap:8px; justify-content:flex-end}
.killrow .btn{padding:7px 13px; font-size:12.5px}

.shell{flex:1; display:grid; grid-template-columns:186px 1fr; min-height:0}
.rail{border-right:1px solid var(--line); padding:22px 0; position:sticky; top:57px; align-self:start}
.rail ol{list-style:none; margin:0; padding:0}
.rail li{position:relative}
.rail button{
  width:100%; display:grid; grid-template-columns:auto 1fr; gap:12px; align-items:baseline;
  background:none; border:0; text-align:left; padding:11px 20px; cursor:pointer; color:var(--ink-3);
  border-left:2px solid transparent;
}
.rail button:hover:not(:disabled){color:var(--ink-2)}
.rail button:disabled{opacity:.34; cursor:not-allowed}
.rail .num{font-family:var(--mono); font-size:11px; letter-spacing:.08em}
.rail .name{font-size:13.5px; letter-spacing:.01em}
.rail li.on button{color:var(--ink); border-left-color:var(--violet); background:linear-gradient(90deg,rgba(139,92,246,.10),transparent)}
.rail li.ok .num{color:var(--ok)}

.stage{padding:34px 40px 90px; min-width:0; max-width:1180px}
.screen{display:none}
.screen.on{display:block; animation:rise .38s cubic-bezier(.2,.7,.3,1) both}
@keyframes rise{ from{opacity:0; transform:translateY(9px)} }

.eyebrow{
  font-family:var(--mono); font-size:10.5px; letter-spacing:.16em; text-transform:uppercase;
  color:var(--violet); margin:0 0 10px;
}
h1{font-size:29px; font-weight:250; letter-spacing:.005em; margin:0 0 8px}
.lede{color:var(--ink-2); margin:0 0 26px; max-width:66ch}
h2{font-size:16px; font-weight:450; margin:30px 0 12px; letter-spacing:.01em}

.panel{background:var(--panel); border:1px solid var(--line); border-radius:var(--r); padding:18px 20px}
.panel + .panel{margin-top:14px}
.muted{color:var(--ink-2)}
.tiny{font-size:12px}

/* --------------------------------------------------------- datasets ------ */
.ds-list{display:grid; gap:8px; margin:0; padding:0; list-style:none}
.ds{
  display:grid; grid-template-columns:1fr auto auto; gap:16px; align-items:center;
  width:100%; text-align:left; padding:14px 16px; cursor:pointer;
  background:var(--panel); border:1px solid var(--line); border-radius:var(--r); color:inherit;
  transition:border-color .16s, background .16s, transform .16s;
}
.ds:hover{border-color:rgba(126,110,255,.42); background:var(--panel-2); transform:translateX(2px)}
.ds .nm{font-family:var(--mono); font-size:13px; overflow:hidden; text-overflow:ellipsis}
.ds .sz{font-family:var(--mono); font-size:12px; color:var(--ink-2)}
.ds .st{font-family:var(--mono); font-size:10.5px; letter-spacing:.1em; text-transform:uppercase; color:var(--ink-3)}
.ds .st.has{color:var(--ok)}
.empty{border:1px dashed var(--line); border-radius:var(--r); padding:26px; text-align:center; color:var(--ink-2)}

)MEROPE_UI",
R"MEROPE_UI(.row{display:flex; flex-wrap:wrap; gap:12px; align-items:flex-end}
.field{display:grid; gap:6px}
.field label{font-family:var(--mono); font-size:10.5px; letter-spacing:.12em; text-transform:uppercase; color:var(--ink-3)}
.control{
  background:var(--panel-2); border:1px solid var(--line); border-radius:8px;
  padding:9px 11px; font-family:var(--mono); font-size:13px; min-width:0;
}
.control:hover{border-color:rgba(126,110,255,.34)}
/* Selects size to their widest option by default, which makes a row of them
   ragged. Give them one width so the controls line up. */
select.control{cursor:pointer; width:100%; min-width:132px}
.field{min-width:132px}
.btn{
  border:1px solid transparent; border-radius:8px; padding:10px 18px; cursor:pointer;
  background:linear-gradient(135deg,var(--violet),var(--blue)); color:#fff; font-weight:500;
  letter-spacing:.01em; transition:filter .16s, transform .12s;
}
.btn:hover:not(:disabled){filter:brightness(1.12)}
.btn:active:not(:disabled){transform:translateY(1px)}
.btn:disabled{opacity:.45; cursor:not-allowed}
.btn.ghost{background:none; border-color:var(--line); color:var(--ink-2)}
.btn.ghost:hover:not(:disabled){border-color:rgba(126,110,255,.44); color:var(--ink)}

/* ----------------------------------------------------------- schema ------ */
.facts{display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:1px; background:var(--line-soft); border:1px solid var(--line); border-radius:var(--r); overflow:hidden}
.fact{background:var(--panel); padding:13px 15px}
.fact dt{font-family:var(--mono); font-size:10px; letter-spacing:.12em; text-transform:uppercase; color:var(--ink-3); margin:0 0 5px}
.fact dd{margin:0; font-family:var(--mono); font-size:13px}
.estimate{color:var(--warn); font-size:11px; font-family:var(--mono)}

.cols{display:grid; gap:10px; margin-top:14px}
/* The signature: every column shows the raw sampled values it was judged on,
   right beside the conclusion drawn from them. */
.col{
  display:grid; grid-template-columns:168px 1fr; gap:0;
  background:var(--panel); border:1px solid var(--line); border-radius:var(--r); overflow:hidden;
}
.col.conf{border-color:rgba(94,234,212,.24)}
.col.unk{border-color:rgba(251,191,36,.28)}
.strip{
  padding:14px 14px 14px 16px; border-right:1px solid var(--line-soft);
  background:linear-gradient(180deg,rgba(139,92,246,.07),transparent 70%);
  display:grid; align-content:start; gap:3px; min-width:0;
}
.strip .sv{
  font-family:var(--mono); font-size:11px; color:var(--ink-2);
  white-space:nowrap; overflow:hidden; text-overflow:ellipsis; opacity:.82;
}
/* The caption is the first child, so the fade starts at the second. Every
   position is listed: an unstyled one would jump back to full strength. */
.strip .sv:nth-child(3){opacity:.68}
.strip .sv:nth-child(4){opacity:.54}
.strip .sv:nth-child(5){opacity:.42}
.strip .sv:nth-child(6){opacity:.30}
.strip .cap{font-family:var(--mono); font-size:9.5px; letter-spacing:.12em; text-transform:uppercase; color:var(--ink-3); margin-bottom:5px}
.col-main{padding:14px 18px; display:grid; gap:11px; min-width:0}
.col-top{display:flex; align-items:center; gap:11px; flex-wrap:wrap}
.idx{font-family:var(--mono); font-size:11px; color:var(--ink-3)}
.pname{font-family:var(--mono); font-size:13.5px}
.pill{
  font-family:var(--mono); font-size:10px; letter-spacing:.1em;
  padding:3px 8px; border-radius:999px; border:1px solid var(--line);
  background:rgba(139,92,246,.09); color:var(--ink-2);
}
.col-edit{display:grid; grid-template-columns:minmax(140px,1.1fr) minmax(130px,.9fr) 168px; gap:10px; align-items:end}
.meterwrap{display:grid; gap:6px}
.meterwrap .lab{display:flex; justify-content:space-between; font-family:var(--mono); font-size:10.5px; color:var(--ink-3); letter-spacing:.08em; text-transform:uppercase}
.meter{height:3px; background:rgba(255,255,255,.07); border-radius:2px; overflow:hidden}
.meter i{display:block; height:100%; background:linear-gradient(90deg,var(--indigo),var(--violet))}
.meter.low i{background:var(--warn)}
.why{margin:0; font-size:12.5px; color:var(--ink-2)}
.why b{color:var(--warn); font-weight:500}
.numbers{display:flex; flex-wrap:wrap; gap:14px; margin:0; font-family:var(--mono); font-size:11.5px; color:var(--ink-3)}
.numbers span b{color:var(--ink-2); font-weight:400}

.notes{margin:12px 0 0; padding:0; list-style:none; display:grid; gap:6px}
.notes li{font-family:var(--mono); font-size:12px; color:var(--ink-2); padding-left:16px; position:relative}
.notes li::before{content:"·"; position:absolute; left:4px; color:var(--violet)}
details.prompt{margin-top:12px}
details.prompt summary{cursor:pointer; font-family:var(--mono); font-size:11.5px; color:var(--ink-2); letter-spacing:.04em}
details.prompt summary:hover{color:var(--ink)}
pre.code{
  margin:10px 0 0; padding:14px; background:#07070f; border:1px solid var(--line);
  border-radius:8px; overflow:auto; font-family:var(--mono); font-size:12px;
  color:var(--ink-2); max-height:340px; line-height:1.55;
}

/* -------------------------------------------------------------- ask ------ */
.ask{display:grid; gap:12px}
.ask-input{
  width:100%; background:var(--panel); border:1px solid var(--line); border-radius:var(--r);
  padding:18px 20px; font-size:17px; font-weight:250; letter-spacing:.005em;
}
.ask-input:hover{border-color:rgba(126,110,255,.34)}
.ask-input::placeholder{color:var(--ink-3)}
.suggest{display:flex; flex-wrap:wrap; gap:7px}
.chip{
  background:none; border:1px solid var(--line); border-radius:999px; padding:6px 13px;
  font-family:var(--mono); font-size:11.5px; color:var(--ink-2); cursor:pointer;
}
.chip:hover{border-color:rgba(126,110,255,.44); color:var(--ink)}

/* The chain is the argument of the whole project: what the model produced, and
   what had to accept it before anything ran. */
.chain{list-style:none; margin:22px 0 0; padding:0; display:flex; flex-wrap:wrap; gap:0}
.chain li{
  position:relative; flex:1 1 130px; min-width:126px; padding:13px 14px 13px 16px;
  border:1px solid var(--line); border-right-width:0; background:var(--panel);
}
.chain li:first-child{border-radius:var(--r) 0 0 var(--r)}
.chain li:last-child{border-right-width:1px; border-radius:0 var(--r) var(--r) 0}
.chain .k{display:flex; align-items:center; gap:7px; font-family:var(--mono); font-size:11px; letter-spacing:.1em; text-transform:uppercase; color:var(--ink-3)}
.chain .v{display:block; margin-top:5px; font-size:12.5px; color:var(--ink-3)}
.chain .dot{width:6px; height:6px; border-radius:50%; background:var(--ink-3); flex:none}
.chain li.is-active{background:var(--panel-2); border-color:rgba(126,110,255,.4)}
.chain li.is-active .k{color:var(--ink)}
.chain li.is-active .dot{background:var(--violet); animation:pulse 1s ease-in-out infinite}
@keyframes pulse{ 50%{ transform:scale(1.6); opacity:.55 } }
.chain li.is-done .k{color:var(--ink-2)}
.chain li.is-done .dot{background:var(--ok)}
.chain li.is-done .v{color:var(--ink-2)}
.chain li.is-blocked{background:rgba(251,113,133,.07); border-color:rgba(251,113,133,.42)}
.chain li.is-blocked .k{color:var(--stop)}
.chain li.is-blocked .dot{background:var(--stop)}
.chain li.is-skipped{opacity:.35}

.verdict{margin-top:16px; border-radius:var(--r); padding:16px 18px; border:1px solid}
.verdict.stop{background:rgba(251,113,133,.07); border-color:rgba(251,113,133,.34)}
.verdict.warn{background:rgba(251,191,36,.06); border-color:rgba(251,191,36,.28)}
.verdict h3{margin:0 0 8px; font-size:14px; font-weight:500}
.verdict.stop h3{color:var(--stop)}
.verdict.warn h3{color:var(--warn)}
.verdict ul{margin:0; padding-left:18px; display:grid; gap:5px}
.verdict li{font-family:var(--mono); font-size:12.5px; color:var(--ink-2)}
.verdict p{margin:10px 0 0; font-size:12.5px; color:var(--ink-2)}

.split{display:grid; grid-template-columns:1fr 1fr; gap:14px}
@media (max-width:1000px){ .split{grid-template-columns:1fr} }

/* ----------------------------------------------------------- result ------ */
.tiles{display:grid; grid-template-columns:repeat(auto-fit,minmax(146px,1fr)); gap:1px; background:var(--line-soft); border:1px solid var(--line); border-radius:var(--r); overflow:hidden}
.tile{background:var(--panel); padding:15px 16px}
.tile dt{font-family:var(--mono); font-size:10px; letter-spacing:.12em; text-transform:uppercase; color:var(--ink-3); margin:0 0 6px}
.tile dd{margin:0; font-size:21px; font-weight:250; letter-spacing:-.01em; font-variant-numeric:tabular-nums}
.tile dd small{font-size:12px; color:var(--ink-2); margin-left:3px; font-weight:400}
.tile.hero{background:linear-gradient(140deg,rgba(139,92,246,.16),rgba(79,124,255,.06))}

figure.chart{margin:0}
figure.chart figcaption{font-size:12.5px; color:var(--ink-2); margin-bottom:12px}
.chart svg{width:100%; height:auto; display:block; overflow:visible}
.chart .grid{stroke:rgba(255,255,255,.06); stroke-width:1}
.chart .axis{fill:var(--ink-3); font-family:var(--mono); font-size:10px}
.chart .cat{fill:var(--ink-2); font-family:var(--mono); font-size:11px}
.chart .val{fill:var(--ink); font-family:var(--mono); font-size:11px}
.chart .bar{transition:opacity .14s}
.chart g.mark:hover .bar{opacity:.82}
.chart g.mark:focus-visible .bar{opacity:.82}

.tablewrap{overflow:auto; border:1px solid var(--line); border-radius:var(--r); max-height:460px}
table{border-collapse:collapse; width:100%; font-family:var(--mono); font-size:12.5px}
thead th{
  position:sticky; top:0; background:var(--panel-2); text-align:left; font-weight:500;
  padding:10px 14px; border-bottom:1px solid var(--line); color:var(--ink-2); white-space:nowrap;
}
thead th .t{display:block; font-size:9.5px; letter-spacing:.1em; color:var(--ink-3); margin-top:2px}
tbody td{padding:8px 14px; border-bottom:1px solid var(--line-soft); white-space:nowrap}
tbody tr:hover td{background:rgba(139,92,246,.06)}
td.num{text-align:right; font-variant-numeric:tabular-nums}

#tip{
  position:fixed; z-index:60; pointer-events:none; opacity:0; transform:translateY(3px);
  background:var(--raise); border:1px solid var(--line); border-radius:7px; padding:8px 11px;
  font-family:var(--mono); font-size:11.5px; box-shadow:0 10px 30px rgba(0,0,0,.55);
  transition:opacity .12s, transform .12s; max-width:280px;
}
#tip.on{opacity:1; transform:translateY(0)}
#tip b{display:block; color:var(--ink); font-weight:500; margin-bottom:2px}
#tip span{color:var(--ink-2)}

.busybar{height:2px; background:rgba(255,255,255,.06); border-radius:2px; overflow:hidden; margin-top:16px}
.busybar i{display:block; height:100%; width:36%; background:linear-gradient(90deg,transparent,var(--violet),transparent); animation:sweep 1.15s ease-in-out infinite}
@keyframes sweep{ from{transform:translateX(-100%)} to{transform:translateX(340%)} }

.toast{
  position:fixed; left:50%; bottom:26px; transform:translate(-50%,14px); z-index:70;
  background:var(--raise); border:1px solid var(--line); border-radius:9px; padding:11px 17px;
)MEROPE_UI",
R"MEROPE_UI(  font-family:var(--mono); font-size:12.5px; opacity:0; transition:opacity .2s, transform .2s;
  box-shadow:0 14px 40px rgba(0,0,0,.6); max-width:min(560px,88vw);
}
.toast.on{opacity:1; transform:translate(-50%,0)}
.toast.bad{border-color:rgba(251,113,133,.5); color:var(--stop)}

/* --------------------------------------------------------------- gone ---- */
/* What is left once the engine is not running. The sky keeps moving behind it,
   because the sky was never the program. */
#gone{
  position:fixed; inset:0; z-index:110; display:grid; place-items:center;
  background:rgba(4,4,10,.80); backdrop-filter:blur(7px); animation:fadein .5s ease both;
}
@keyframes fadein{ from{opacity:0} }
.gone-inner{display:grid; justify-items:center; gap:18px; text-align:center; padding:0 22px}
.gone-mark{
  font-family:var(--sans); font-weight:200; font-size:clamp(38px,7vw,74px); line-height:1;
  letter-spacing:.02em; color:rgba(233,233,246,.26);
}
.gone-line{margin:0; font-size:15.5px; color:var(--ink)}
.gone-sub{
  margin:0; font-family:var(--mono); font-size:11px; letter-spacing:.12em;
  text-transform:uppercase; color:var(--ink-3);
}
.gone-hint{
  margin:4px 0 0; font-family:var(--mono); font-size:12.5px; color:var(--ink-2);
  border:1px solid var(--line); border-radius:8px; padding:10px 14px; background:var(--panel);
  max-width:min(560px,88vw); overflow:auto;
}

@media (max-width:820px){
  .shell{grid-template-columns:1fr}
  .rail{position:static; border-right:0; border-bottom:1px solid var(--line); padding:8px 0}
  .rail ol{display:flex; overflow:auto}
  .rail button{border-left:0; border-bottom:2px solid transparent; white-space:nowrap}
  .rail li.on button{border-left-color:transparent; border-bottom-color:var(--violet)}
  .stage{padding:24px 18px 70px}
  .col{grid-template-columns:1fr}
  .strip{border-right:0; border-bottom:1px solid var(--line-soft)}
  .col-edit{grid-template-columns:1fr}
}
@media (prefers-reduced-motion:reduce){
  *,*::before,*::after{animation-duration:.001s !important; animation-iteration-count:1 !important; transition-duration:.001s !important}
  .g::after{clip-path:inset(0 0 0 0)}
}
</style>
</head>
<body>

<svg id="sky" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
  <defs>
    <radialGradient id="glow">
      <stop offset="0%" stop-color="#ffffff" stop-opacity=".50"/>
      <stop offset="35%" stop-color="#c7d2fe" stop-opacity=".16"/>
      <stop offset="100%" stop-color="#4f7cff" stop-opacity="0"/>
    </radialGradient>
    <!-- NGC 1435, the reflection nebula around Merope. It is blue because dust
         scatters her light; that is why this one gets a halo and the rest do not. -->
    <radialGradient id="nebula">
      <stop offset="0%" stop-color="#8ab4ff" stop-opacity=".30"/>
      <stop offset="45%" stop-color="#6366f1" stop-opacity=".12"/>
      <stop offset="100%" stop-color="#4f7cff" stop-opacity="0"/>
    </radialGradient>
    <!-- A meteor is bright at the head and gone at the tail, which is the one
         thing that tells the eye which way it is going. -->
    <linearGradient id="meteorGrad" x1="0" y1="1" x2="1" y2="0">
      <stop offset="0%" stop-color="#ffffff" stop-opacity=".95"/>
      <stop offset="55%" stop-color="#c7d2fe" stop-opacity=".35"/>
      <stop offset="100%" stop-color="#8b5cf6" stop-opacity="0"/>
    </linearGradient>
  </defs>
  <!-- Three depths, drawn back to front. Each is one group, so a frame of
       parallax is three attribute writes rather than two hundred. -->
  <g id="skyField"></g>
  <g id="skyCluster"></g>
  <g id="skyMeteors"></g>
</svg>

<div id="boot">
  <div class="boot-inner">
    <div class="wordmark" role="img" aria-label="merope">
      <span class="g" data-ch="m" style="--i:0">m</span>
      <span class="g" data-ch="e" style="--i:1">e</span>
      <span class="g" data-ch="r" style="--i:2">r</span>
      <svg class="ring" id="bootRing" viewBox="0 0 100 100" aria-hidden="true">
        <defs>
          <linearGradient id="ringGrad" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="#8b5cf6"/><stop offset="100%" stop-color="#4f7cff"/>
          </linearGradient>
        </defs>
        <circle class="track" cx="50" cy="50" r="42"/>
        <circle class="arc" id="bootArc" cx="50" cy="50" r="42"
                stroke-dasharray="264" stroke-dashoffset="238"/>
      </svg>
      <span class="g" data-ch="p" style="--i:4">p</span>
      <span class="g" data-ch="e" style="--i:5">e</span>
    </div>
    <div class="boot-meta">
      <div class="boot-rule"><i id="bootBar"></i></div>
      <div class="boot-status" id="bootStatus">starting the engine</div>
    </div>
  </div>
</div>

<div id="app" hidden>
  <header class="topbar">
    <div class="brand" id="brand">
      <span>mer</span>
      <svg class="ring" viewBox="0 0 100 100" aria-hidden="true">
        <circle class="track" cx="50" cy="50" r="42"/>
        <circle class="arc" cx="50" cy="50" r="42" stroke-dasharray="264" stroke-dashoffset="190"/>
      </svg>
      <span>pe</span>
    </div>
    <div class="crumb" id="crumb"><span class="muted">no dataset</span></div>
    <div class="spacer"></div>
    <span class="tag" id="aiTag" title="the model answering here">mock provider</span>
    <span class="tag live" id="engineTag">engine ready</span>

    <!-- Hidden until the session says this server allows it: a server started
         with --no-kill offers no button rather than a button that fails. -->
    <div class="killwrap" id="killWrap" hidden>
      <button class="btn kill" id="killBtn" aria-haspopup="dialog" aria-expanded="false"
              title="Stop the merope process serving this page">
        <svg viewBox="0 0 24 24" aria-hidden="true">
          <path d="M12 3v9"/>
          <path d="M18.4 6.6a9 9 0 1 1-12.8 0"/>
        </svg>
        Kill
      </button>
      <div class="killpop" id="killPop" role="dialog" aria-label="Stop the engine" hidden>
        <b>Stop the engine?</b>
        <p>The process ends. This page stays where it is, but nothing will answer it.
           Start it again with <code id="killHint">merope serve</code>.</p>
        <div class="killrow">
          <button class="btn ghost" id="killNo">Keep running</button>
          <button class="btn danger" id="killYes">Kill it</button>
        </div>
      </div>
    </div>
  </header>

  <div class="shell">
    <nav class="rail" aria-label="Workflow">
      <ol id="rail">
        <li class="on"><button data-step="1"><span class="num">01</span><span class="name">Dataset</span></button></li>
        <li><button data-step="2" disabled><span class="num">02</span><span class="name">Schema</span></button></li>
        <li><button data-step="3" disabled><span class="num">03</span><span class="name">Ask</span></button></li>
        <li><button data-step="4" disabled><span class="num">04</span><span class="name">Result</span></button></li>
      </ol>
    </nav>

    <main class="stage">
      <!-- 01 ------------------------------------------------------------ -->
      <section class="screen on" id="s1">
        <p class="eyebrow">Step one</p>
        <h1>Pick a dataset</h1>
        <p class="lede">merope reads CSV files it has never seen. It works out the delimiter,
          the encoding, whether there is a header, and what every column holds, from a sample
          rather than a full scan.</p>

        <ul class="ds-list" id="dsList"></ul>

        <h2>Or write a synthetic one</h2>
        <div class="panel">
          <p class="tiny muted" style="margin:0 0 14px">The generator records the exact totals it
            writes, so you can check the engine's answers against the data rather than against
            another run of the engine.</p>
          <div class="row">
            <div class="field"><label for="genName">File name</label>
              <input class="control" id="genName" value="sales.csv" size="16"></div>
            <div class="field"><label for="genRows">Rows</label>
              <input class="control" id="genRows" type="number" value="500000" min="1" max="50000000" step="1000" size="10"></div>
            <div class="field"><label for="genCorrupt">Broken rows</label>
              <select class="control" id="genCorrupt">
                <option value="0">none</option>
                <option value="0.01">1%</option>
                <option value="0.05">5%</option>
              </select></div>
            <div class="field"><label for="genHeader">Header row</label>
              <select class="control" id="genHeader">
                <option value="1">yes</option>
                <option value="0">no, infer everything</option>
              </select></div>
            <button class="btn" id="genBtn">Write it</button>
          </div>
          <div id="genOut"></div>
        </div>
      </section>

      <!-- 02 ------------------------------------------------------------ -->
      <section class="screen" id="s2">
        <p class="eyebrow">Step two</p>
        <h1>Check what it inferred</h1>
        <p class="lede">Each column is shown next to the sampled values it was judged on. Nothing
          reaches the engine until you confirm it, and <span class="mono">UNKNOWN</span> is a
          legitimate answer where the evidence does not support a guess.</p>
        <div id="schemaBody"></div>
      </section>

      <!-- 03 ------------------------------------------------------------ -->
      <section class="screen" id="s3">
        <p class="eyebrow">Step three</p>
        <h1>Ask a question</h1>
        <p class="lede">The model returns a plan, never code. The validator checks every column and
          every type against the confirmed schema before the engine touches a byte.</p>

        <div class="ask">
          <input class="ask-input" id="q" placeholder="Show total amount by country in 2025"
                 autocomplete="off" spellcheck="false">
          <div class="suggest" id="suggest"></div>
          <div class="row" style="margin-top:4px">
            <div class="field"><label for="workers">Workers</label>
              <select class="control" id="workers"></select></div>
            <div class="field"><label for="parts">Partitions</label>
              <select class="control" id="parts"></select></div>
            <div class="field"><label for="policy">Broken rows</label>
              <select class="control" id="policy">
                <option value="skip">skip and count</option>
                <option value="quarantine">quarantine</option>
                <option value="fail">stop the query</option>
              </select></div>
            <div class="field" id="modelField" hidden><label for="model">Model</label>
              <select class="control" id="model"></select></div>
            <div class="field"><label for="baseline">Baseline</label>
              <select class="control" id="baseline">
                <option value="0">parallel only</option>
)MEROPE_UI",
R"MEROPE_UI(                <option value="1">also time single threaded</option>
              </select></div>
            <button class="btn" id="runBtn">Run</button>
          </div>
        </div>

        <ol class="chain" id="chain"></ol>
        <div id="askOut"></div>
      </section>

      <!-- 04 ------------------------------------------------------------ -->
      <section class="screen" id="s4">
        <p class="eyebrow">Step four</p>
        <h1>Result</h1>
        <div id="resultBody"></div>
      </section>
    </main>
  </div>
</div>

<div id="gone" hidden>
  <div class="gone-inner">
    <div class="gone-mark">merope</div>
    <p class="gone-line" id="goneLine">the engine is stopping</p>
    <p class="gone-sub" id="goneSub">asking the port</p>
    <p class="gone-hint mono" id="goneHint">merope serve</p>
  </div>
</div>

<div id="tip" role="tooltip" aria-hidden="true"></div>
<div class="toast" id="toast" role="status" aria-live="polite"></div>

<script>
"use strict";
const $ = (s, r) => (r || document).querySelector(s);
const $$ = (s, r) => Array.from((r || document).querySelectorAll(s));
const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const wait = ms => new Promise(r => setTimeout(r, reduced ? 0 : ms));

const SEMANTIC_TYPES = ["UNKNOWN","IDENTIFIER","QUANTITY","MONETARY","PERCENTAGE","COUNTRY",
                        "CATEGORY","STATUS","DATE","TIMESTAMP","TEXT","FLAG","EMAIL"];

const state = { datasets: [], path: null, inspect: null, outcome: null, step: 1, busy: false,
                session: null, dead: false, models: null };

/* ------------------------------------------------------------------ sky --- */
/* The Pleiades, M45. Positions are J2000 right ascension and declination taken
   as offsets from Alcyone, with the RA offset multiplied by cos(dec) so the
   projection is not stretched, then divided by one common scale so the cluster
   keeps its real shape. Magnitude is apparent visual magnitude: lower is
   brighter. Merope is the one this is named after. */
const PLEIADES = [
  { name: "Alcyone",  x: 0.385, y: 0.738, mag: 2.87 },
  { name: "Atlas",    x: 0.000, y: 0.790, mag: 3.62 },
  { name: "Electra",  x: 0.984, y: 0.730, mag: 3.70 },
  { name: "Maia",     x: 0.765, y: 0.474, mag: 3.87 },
  { name: "Merope",   x: 0.650, y: 0.896, mag: 4.14 },
  { name: "Taygeta",  x: 0.907, y: 0.374, mag: 4.30 },
  { name: "Pleione",  x: -0.006, y: 0.706, mag: 5.05 },
  { name: "Celaeno",  x: 1.000, y: 0.553, mag: 5.45 },
  { name: "Asterope", x: 0.747, y: 0.286, mag: 5.76 },
  { name: "18 Tauri", x: 0.918, y: 0.000, mag: 5.64 },
  { name: "22 Tauri", x: 0.714, y: 0.313, mag: 6.43 }
];

// Where the cluster sits inside the 100x100 viewBox.
const SKY_LEFT = 62, SKY_TOP = 12, SKY_SPAN = 46;

/* The field is drawn at three depths. Nearer stars are larger, brighter, and
   swing further; the far layer barely moves at all. The cluster belongs to
   none of them: at 444 light years it is effectively at infinity, so it never
   parallaxes and only ever moves as one rigid body. Its shape is data, and
   data does not get stretched to look livelier. */
const SKY_DEPTHS = [
  { count: 116, depth: 0.26, minRadius: 0.026, maxRadius: 0.055, minDim: 0.10, maxDim: 0.34 },
  { count:  78, depth: 0.58, minRadius: 0.040, maxRadius: 0.080, minDim: 0.16, maxDim: 0.46 },
  { count:  36, depth: 1.00, minRadius: 0.058, maxRadius: 0.110, minDim: 0.24, maxDim: 0.62 }
];

const sky = { layers: [], cluster: null, meteors: null,
              aim: { x: 0, y: 0 }, at: { x: 0, y: 0 } };

// A seeded generator, so the field stars are in the same place on every load.
function mulberry32(seed){
  return function(){
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function svgNode(name, attributes){
  const node = document.createElementNS("http://www.w3.org/2000/svg", name);
  for (const key in attributes) node.setAttribute(key, attributes[key]);
  return node;
}

function buildSky(){
  const field = $("#skyField");
  const cluster = $("#skyCluster");
  if (!field || !cluster) return;
  const random = mulberry32(0x4D45524F);

  // Background field: far more stars than the cluster, all faint. Drawn wider
  // and taller than the viewBox, so a drifting layer never shows an edge.
  for (const spec of SKY_DEPTHS){
    const layer = svgNode("g", {});
    for (let index = 0; index < spec.count; index++){
      const star = svgNode("circle", {
        class: "field",
        cx: (-34 + random() * 168).toFixed(2),
        cy: (-10 + random() * 120).toFixed(2),
        r: (spec.minRadius + random() * (spec.maxRadius - spec.minRadius)).toFixed(3),
        opacity: (spec.minDim + random() * (spec.maxDim - spec.minDim)).toFixed(2)
      });
      // Roughly a fifth twinkle, each on its own clock. A field where every
      // star breathes in step reads as a flicker rather than as a sky.
      if (!reduced && random() < 0.22){
        star.setAttribute("class", "field twinkle");
        star.style.animationDelay = (random() * 6).toFixed(2) + "s";
        star.style.animationDuration = (3.4 + random() * 4.8).toFixed(2) + "s";
      }
      layer.appendChild(star);
    }
    field.appendChild(layer);
    sky.layers.push({ node: layer, depth: spec.depth, phase: random() * 6.283 });
  }

  for (const star of PLEIADES){
    const cx = SKY_LEFT + star.x * SKY_SPAN;
    const cy = SKY_TOP + star.y * SKY_SPAN;
    // Magnitude is logarithmic and inverted; this maps the range 2.9 to 6.4
    // onto a radius that stays readable at both ends.
    const radius = 0.075 + Math.pow(Math.max(0, 6.8 - star.mag) / 3.9, 1.35) * 0.28;
    const isMerope = star.name === "Merope";
    const group = svgNode("g", {});

    if (isMerope){
      group.appendChild(svgNode("circle", { class: "neb", cx, cy, r: 5.2, fill: "url(#nebula)" }));
    }
    group.appendChild(svgNode("circle", {
      cx, cy, r: (radius * 10).toFixed(2), fill: "url(#glow)",
      opacity: isMerope ? 0.95 : 0.6
    }));

    // Diffraction spikes on the brightest few, the way a camera would see them.
    if (star.mag < 4.2){
      const reach = radius * 9;
      group.appendChild(svgNode("line", {
        class: "spike", x1: cx - reach, y1: cy, x2: cx + reach, y2: cy,
        "stroke-width": (radius * 0.18).toFixed(3)
      }));
      group.appendChild(svgNode("line", {
        class: "spike", x1: cx, y1: cy - reach, x2: cx, y2: cy + reach,
        "stroke-width": (radius * 0.18).toFixed(3)
      }));
    }

    group.appendChild(svgNode("circle", {
      class: "core", cx, cy, r: radius.toFixed(3),
      opacity: isMerope ? 1 : 0.9
    }));

    if (isMerope){
      const label = svgNode("text", { class: "name", x: cx + radius + 1.6, y: cy + 0.45 });
      label.textContent = "merope";
      group.appendChild(label);
    }
    cluster.appendChild(group);
  }

  sky.cluster = cluster;
  sky.meteors = $("#skyMeteors");
}

/* The sky turns, the way it does overhead, except on a scale of minutes rather
   than hours. Nothing is animated per star: a frame is four transform writes,
   three layers and the cluster, whatever the field cost to draw once. */
function animateSky(){
  if (reduced || !sky.layers.length) return;

  const centreX = SKY_LEFT + SKY_SPAN * 0.50;
  const centreY = SKY_TOP + SKY_SPAN * 0.55;
  const started = performance.now();

  const frame = now => {
    const t = (now - started) / 1000;
    // The pointer only nudges, and it eases: moving the mouse should never
    // yank the background out from under what you are reading.
    sky.at.x += (sky.aim.x - sky.at.x) * 0.05;
    sky.at.y += (sky.aim.y - sky.at.y) * 0.05;

    for (const layer of sky.layers){
      const swing = 3.2 * layer.depth;
      const x = Math.sin(t * 0.021 + layer.phase) * swing + sky.at.x * 3.0 * layer.depth;
      const y = Math.cos(t * 0.016 + layer.phase) * swing * 0.42 + sky.at.y * 1.9 * layer.depth;
      layer.node.setAttribute("transform",
        "translate(" + x.toFixed(3) + " " + y.toFixed(3) + ")");
    }

    // The cluster drifts and turns about its own centre. No scale, and no
    // motion of one member relative to another.
    const dx = Math.sin(t * 0.019 + 1.1) * 0.9 + sky.at.x * 0.7;
    const dy = Math.cos(t * 0.013 + 0.4) * 0.6 + sky.at.y * 0.45;
    const turn = Math.sin(t * 0.011) * 1.5;
    sky.cluster.setAttribute("transform",
      "translate(" + dx.toFixed(3) + " " + dy.toFixed(3) + ") " +
      "rotate(" + turn.toFixed(3) + " " + centreX.toFixed(2) + " " + centreY.toFixed(2) + ")");

    requestAnimationFrame(frame);
  };
  // A hidden tab gets no frames, so a page left open overnight costs nothing.
  requestAnimationFrame(frame);

  window.addEventListener("pointermove", event => {
    sky.aim.x = (event.clientX / window.innerWidth) * 2 - 1;
    sky.aim.y = (event.clientY / window.innerHeight) * 2 - 1;
  }, { passive: true });
}

/* One meteor at a time, drawn when it is due and removed when it lands, so an
   hour of uptime holds no more nodes than a minute of it. Frequent enough to
   be seen, rare enough to stay an event. */
function meteor(){
  if (!sky.meteors || document.hidden) return;
  // Kept inside the box the viewer actually sees: the head starts on screen
  // even on a narrow window, and travels down and to the left from there.
  const x = 26 + Math.random() * 68;
  const y = -4 + Math.random() * 44;
  const length = 8 + Math.random() * 14;
  const group = svgNode("g", { class: "meteor" });
  // The head is the end it travels towards; the gradient fades from there back
  // along the trail, which is what tells the eye which way it is going.
  group.appendChild(svgNode("line", {
    x1: (x - length).toFixed(2), y1: (y + length * 0.55).toFixed(2),
    x2: x.toFixed(2), y2: y.toFixed(2),
    stroke: "url(#meteorGrad)",
    "stroke-width": (0.10 + Math.random() * 0.10).toFixed(3),
    "stroke-linecap": "round"
  }));
  group.style.animationDuration = (0.95 + Math.random() * 0.55).toFixed(2) + "s";
  group.addEventListener("animationend", () => group.remove());
  sky.meteors.appendChild(group);
}

function scheduleMeteors(){
  if (reduced) return;
  setTimeout(() => { meteor(); scheduleMeteors(); }, 11000 + Math.random() * 26000);
}

/* ---------------------------------------------------------------- utils --- */
function esc(s){ return String(s == null ? "" : s).replace(/[&<>"']/g, c =>
  ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c])); }

function fmtInt(n){ return Number(n || 0).toLocaleString("en-US"); }

function fmtCompact(n){
  const a = Math.abs(n);
  if (a >= 1e9) return (n/1e9).toFixed(a >= 1e10 ? 0 : 1) + "B";
  if (a >= 1e6) return (n/1e6).toFixed(a >= 1e7 ? 0 : 1) + "M";
  if (a >= 1e3) return (n/1e3).toFixed(a >= 1e4 ? 0 : 1) + "k";
  return a >= 100 ? n.toFixed(0) : n.toFixed(2).replace(/\.?0+$/, "");
}

)MEROPE_UI",
R"MEROPE_UI(// The optional headers exist for one caller: the kill button, which has to
// prove it is the page this server sent and not a form on another site.
async function api(method, path, body, headers){
  const options = { method, headers: Object.assign({}, headers || {}) };
  if (body !== undefined){ options.headers["Content-Type"] = "application/json";
                           options.body = JSON.stringify(body); }
  const response = await fetch(path, options);
  let payload;
  try { payload = await response.json(); }
  catch (e) { throw new Error("the engine returned something that was not JSON"); }
  if (!response.ok || payload.ok === false) throw new Error(payload.error || ("request failed: " + response.status));
  return payload;
}

let toastTimer = 0;
function toast(message, bad){
  const node = $("#toast");
  node.textContent = message;
  node.classList.toggle("bad", !!bad);
  node.classList.add("on");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => node.classList.remove("on"), bad ? 7000 : 3600);
}

function busy(on){
  state.busy = on;
  $("#brand").classList.toggle("busy", on);
  $("#engineTag").textContent = on ? "working" : "engine ready";
  $("#engineTag").classList.toggle("live", !on);
}

/* ---------------------------------------------------------------- model --- */
/* Which model answers, and the freedom to pick another one. The server decides
   the provider, the endpoint and the key; the page decides only the model, and
   only from the list that provider says this key may use. */
function renderProvider(){
  const ai = (state.session && state.session.ai) || null;
  const tag = $("#aiTag");
  if (!ai){
    tag.textContent = "no provider";
    return;
  }
  tag.textContent = ai.remote ? ai.provider + " · " + ai.model : "mock provider";
  tag.title = ai.remote
    ? "answers come from " + ai.provider + ":" + ai.model + " (" + ai.source + ")"
    : (ai.note || "no model configured; the built in heuristics are answering");
  tag.classList.toggle("live", !!ai.remote);

  // The picker only appears when there is something to pick between.
  if (!ai.remote) return;
  $("#modelField").hidden = false;
  fillModelSelect([ai.model], ai.model);
}

function fillModelSelect(models, current){
  const select = $("#model");
  const options = models.map(name =>
    '<option value="' + esc(name) + '"' + (name === current ? " selected" : "") + ">" +
    esc(name) + "</option>").join("");
  // Listing costs a round trip to the provider, so it happens when it is asked
  // for rather than on every load.
  select.innerHTML = options + '<option value="__list__">list what this key can use…</option>';
}

async function loadModels(){
  const select = $("#model");
  const current = state.chosenModel || (state.session.ai && state.session.ai.model) || "";
  select.disabled = true;
  try {
    const listing = await api("GET", "/api/models");
    if (!listing.listed) throw new Error(listing.error || "the provider would not list its models");
    state.models = listing.models || [];
    fillModelSelect(state.models, current);
    toast(state.models.length + " models this key can use");
  } catch (error) {
    fillModelSelect([current], current);
    toast(error.message, true);
  } finally {
    select.disabled = false;
    select.value = current;
  }
}

$("#model").addEventListener("change", () => {
  const select = $("#model");
  if (select.value === "__list__"){ loadModels(); return; }
  state.chosenModel = select.value;
  // The tag is the honest record of what answered, so it moves with the choice.
  if (state.session && state.session.ai){
    $("#aiTag").textContent = state.session.ai.provider + " · " + select.value;
  }
});

// Sent with every request that may reach a model. Empty means "whatever the
// server was started with", which is the only thing the server will accept
// besides a model name.
function chosenModel(){
  return state.chosenModel || "";
}

/* ----------------------------------------------------------------- kill --- */
/* The only control on the page that acts on the server rather than on a
   dataset. It asks before it fires, it carries the session token so a page on
   another site cannot fire it, and afterwards it checks the port rather than
   believing the reply: the process states its intention, the silence is the
   proof. */
function restartCommand(){
  const root = (state.session && state.session.root) || state.root || ".";
  return "merope serve --data " + (/\s/.test(root) ? '"' + root + '"' : root);
}

function killPopOpen(open){
  $("#killPop").hidden = !open;
  $("#killBtn").setAttribute("aria-expanded", open ? "true" : "false");
  if (open) setTimeout(() => $("#killNo").focus(), 0);
}

async function portWentQuiet(){
  // A fetch that fails at the network layer is the answer being looked for:
  // nothing is listening. A 403 or a 500 would still mean something answered.
  for (let attempt = 0; attempt < 16; attempt++){
    try { await fetch("/api/session", { cache: "no-store" }); }
    catch (error) { return true; }
    await new Promise(resolve => setTimeout(resolve, 240));
  }
  return false;
}

async function killEngine(){
  if (!state.session || !state.session.can_shutdown || state.dead) return;
  killPopOpen(false);
  $("#killBtn").disabled = true;
  state.dead = true;

  let refusal = "";
  try {
    await api("POST", "/api/shutdown", {}, { "X-Merope-Token": state.session.token });
  } catch (error) {
    // The socket closing mid reply looks the same from here as a refusal, so
    // the port check below is what decides which of the two it was.
    refusal = error.message;
  }

  $("#engineTag").textContent = "engine stopping";
  $("#engineTag").classList.remove("live");
  $("#engineTag").classList.add("dead");
  $("#goneHint").textContent = restartCommand();
  $("#gone").hidden = false;

  const quiet = await portWentQuiet();
  if (quiet){
    $("#engineTag").textContent = "engine stopped";
    $("#goneLine").textContent = "the engine has stopped";
    $("#goneSub").textContent = "port " + (state.session.port || "") + " no longer answers";
    return;
  }

  // It said no, or it said nothing and kept listening. Give the page back.
  state.dead = false;
  $("#gone").hidden = true;
  $("#killBtn").disabled = false;
  $("#engineTag").textContent = "engine ready";
  $("#engineTag").classList.remove("dead");
  $("#engineTag").classList.add("live");
  toast(refusal || "the port is still answering; stop it with Ctrl+C in the terminal", true);
}

$("#killBtn").addEventListener("click", () => killPopOpen($("#killPop").hidden));
$("#killNo").addEventListener("click", () => killPopOpen(false));
$("#killYes").addEventListener("click", killEngine);
document.addEventListener("keydown", event => {
  if (event.key === "Escape") killPopOpen(false);
});
// Anywhere outside the button and its dialog closes it. The button handler runs
// first, so opening it does not immediately close it again.
document.addEventListener("click", event => {
  if (!$("#killPop").hidden && !event.target.closest("#killWrap")) killPopOpen(false);
});

/* ----------------------------------------------------------------- boot --- */
function bootProgress(fraction, label){
  $("#bootBar").style.width = Math.round(fraction * 100) + "%";
  // The ring arc is the same progress, so the o is not decorative.
  $("#bootArc").setAttribute("stroke-dashoffset", String(264 - 264 * Math.max(0.08, fraction)));
  if (label) $("#bootStatus").textContent = label;
}

async function boot(){
  const started = Date.now();
  try {
    bootProgress(0.14, "starting the engine");
    await wait(420);
    bootProgress(0.42, "reading the data directory");
    const listing = await api("GET", "/api/datasets");
    state.datasets = listing.datasets || [];
    state.root = listing.root || "";
    // What this process permits. A server started with --no-kill offers no
    // kill button at all, rather than one that fails when it is pressed.
    try {
      state.session = await api("GET", "/api/session");
      if (state.session.can_shutdown){
        $("#killWrap").hidden = false;
        $("#killHint").textContent = restartCommand();
      }
      renderProvider();
    } catch (error) {
      state.session = null;
    }
    bootProgress(0.74, "found " + state.datasets.length + " dataset" + (state.datasets.length === 1 ? "" : "s"));
    await wait(520);
    bootProgress(1, "ready");
    // Let the wordmark finish drawing even when the engine answered instantly.
    const elapsed = Date.now() - started;
    await wait(Math.max(0, 2500 - elapsed));
  } catch (error) {
    $("#bootStatus").classList.add("bad");
    bootProgress(1, "cannot reach the engine");
    await wait(1600);
  }
  $("#boot").classList.add("done");
  $("#app").hidden = false;
  renderDatasets();
  buildRunControls();
  setTimeout(() => $("#boot").remove(), 900);

  // A link can name a dataset, and optionally the question to ask about it, so
  // a result is something you can send to someone.
  const link = readLink();
  if (link.path) {
    await inspect(link.path);
    if (link.question && state.inspect) {
      $("#q").value = link.question;
      runQuery();
    }
  }
}

function readLink(){
  const hash = decodeURIComponent(location.hash.replace(/^#/, ""));
  if (!hash) return {};
  const split = hash.indexOf("?q=");
  if (split < 0) return { path: hash };
  return { path: hash.slice(0, split), question: hash.slice(split + 3) };
}

function writeLink(){
  if (!state.path) return;
  const question = $("#q").value.trim();
  const hash = encodeURIComponent(state.path) + (question ? "?q=" + encodeURIComponent(question) : "");
  history.replaceState(null, "", "#" + hash);
}

/* ------------------------------------------------------------ navigation -- */
function go(step){
  state.step = step;
  $$(".screen").forEach(s => s.classList.remove("on"));
  $("#s" + step).classList.add("on");
  $$("#rail li").forEach((li, index) => li.classList.toggle("on", index + 1 === step));
  if (step === 3) setTimeout(() => $("#q").focus(), 60);
  window.scrollTo({ top: 0, behavior: reduced ? "auto" : "smooth" });
}

function unlock(step, done){
  const button = $('#rail button[data-step="' + step + '"]');
  if (button) button.disabled = false;
  if (done) button.closest("li").classList.add("ok");
}

$("#rail").addEventListener("click", event => {
  const button = event.target.closest("button[data-step]");
  if (button && !button.disabled) go(Number(button.dataset.step));
});

/* -------------------------------------------------------------- datasets -- */
function renderDatasets(){
  const host = $("#dsList");
  if (!state.datasets.length){
    host.innerHTML = '<li class="empty">No CSV files in <span class="mono">' +
      esc(state.root || "the data directory") + "</span> yet. Write one below.</li>";
    return;
  }
  host.innerHTML = state.datasets.map(d => (
    '<li><button class="ds" data-path="' + esc(d.path) + '">' +
)MEROPE_UI",
R"MEROPE_UI(      '<span class="nm">' + esc(d.path) + "</span>" +
      '<span class="sz">' + esc(d.size) + "</span>" +
      '<span class="st' + (d.has_schema ? " has" : "") + '">' +
        (d.has_schema ? "schema confirmed" : "not inspected") + "</span>" +
    "</button></li>"
  )).join("");
}

$("#dsList").addEventListener("click", event => {
  const button = event.target.closest(".ds");
  if (button) inspect(button.dataset.path);
});

$("#genBtn").addEventListener("click", async () => {
  const button = $("#genBtn");
  button.disabled = true;
  busy(true);
  $("#genOut").innerHTML = '<div class="busybar"><i></i></div>';
  try {
    const result = await api("POST", "/api/generate", {
      path: $("#genName").value.trim() || "sales.csv",
      rows: Number($("#genRows").value) || 200000,
      corrupt: Number($("#genCorrupt").value),
      header: $("#genHeader").value === "1"
    });
    $("#genOut").innerHTML =
      '<dl class="facts" style="margin-top:14px">' +
        '<div class="fact"><dt>Rows</dt><dd>' + fmtInt(result.rows) + "</dd></div>" +
        '<div class="fact"><dt>Size</dt><dd>' + esc(result.size) + "</dd></div>" +
        '<div class="fact"><dt>Broken rows</dt><dd>' + fmtInt(result.corrupted) + "</dd></div>" +
        '<div class="fact"><dt>True sum of amount</dt><dd>' + esc(result.exact_total_amount) + "</dd></div>" +
        '<div class="fact"><dt>True rows in 2025</dt><dd>' + fmtInt(result.rows_in_2025) + "</dd></div>" +
      "</dl>";
    const listing = await api("GET", "/api/datasets");
    state.datasets = listing.datasets || [];
    renderDatasets();
    toast("Wrote " + result.path + ". Pick it above to inspect it.");
  } catch (error) {
    $("#genOut").innerHTML = "";
    toast(error.message, true);
  }
  button.disabled = false;
  busy(false);
});

/* ---------------------------------------------------------------- schema -- */
async function inspect(path){
  busy(true);
  $("#schemaBody").innerHTML = '<div class="panel"><p class="muted tiny" style="margin:0">' +
    "Sniffing the format, sampling the file and profiling every column…</p>" +
    '<div class="busybar"><i></i></div></div>';
  unlock(2);
  go(2);
  try {
    const data = await api("POST", "/api/inspect", { path, model: chosenModel() });
    state.path = path;
    state.inspect = data;
    $("#crumb").innerHTML = '<b>' + esc(data.path) + "</b><span class='sep'>·</span><span>" +
      esc(data.file_size) + "</span><span class='sep'>·</span><span>" +
      fmtInt(data.dialect.column_count) + " columns</span>";
    renderSchema(data);
    unlock(3);
    buildSuggestions();
  } catch (error) {
    $("#schemaBody").innerHTML = '<div class="verdict stop"><h3>Could not read that file</h3>' +
      "<p>" + esc(error.message) + "</p></div>";
    toast(error.message, true);
  }
  busy(false);
}

function typeOptions(selected){
  return SEMANTIC_TYPES.map(t =>
    '<option value="' + t + '"' + (t === selected ? " selected" : "") + ">" + t + "</option>").join("");
}

function renderSchema(data){
  const sampling = data.sampling;
  const estimate = sampling.exact ? "" : ' <span class="estimate">estimate</span>';

  const facts =
    '<dl class="facts">' +
      '<div class="fact"><dt>Delimiter</dt><dd>' + esc(data.dialect.delimiter) + "</dd></div>" +
      '<div class="fact"><dt>Encoding</dt><dd>' + esc(data.dialect.encoding) + "</dd></div>" +
      '<div class="fact"><dt>Header row</dt><dd>' + (data.dialect.has_header ? "yes" : "no") + "</dd></div>" +
      '<div class="fact"><dt>Decimal mark</dt><dd>' + esc(data.dialect.decimal_separator) + "</dd></div>" +
      '<div class="fact"><dt>Sample</dt><dd>' + fmtInt(sampling.rows) + " rows</dd></div>" +
      '<div class="fact"><dt>Rows in file</dt><dd>' +
        (sampling.exact ? fmtInt(sampling.estimated_total_rows)
                        : "~" + fmtInt(sampling.estimated_total_rows)) + estimate + "</dd></div>" +
    "</dl>";

  const method =
    '<div class="panel" style="margin-top:14px">' +
      '<div class="mono tiny muted">Sampling: ' + esc(sampling.method) +
      " · seed " + esc(sampling.seed) + "</div>" +
      '<ul class="notes">' + (data.format_notes || []).map(n => "<li>" + esc(n) + "</li>").join("") + "</ul>" +
    "</div>";

  const columns = data.columns.map(column => {
    const stats = column.stats || {};
    const examples = (stats.examples || []).slice(0, 5);
    const unknown = column.semantic_type === "UNKNOWN";
    const confidencePercent = Math.round((column.confidence || 0) * 100);

    const numbers = [];
    if (stats.null_count != null) numbers.push("<span>nulls <b>" + fmtInt(stats.null_count) + "</b></span>");
    if (stats.unique_count != null) numbers.push("<span>distinct <b>" + fmtInt(stats.unique_count) +
      (stats.unique_exact === false ? "+" : "") + "</b></span>");
    if (stats.min != null) numbers.push("<span>min <b>" + esc(stats.min) + "</b></span>");
    if (stats.max != null) numbers.push("<span>max <b>" + esc(stats.max) + "</b></span>");
    if (stats.mean != null) numbers.push("<span>mean <b>" + fmtCompact(stats.mean) + "</b></span>");
    if (stats.date_pattern) numbers.push("<span>pattern <b>" + esc(stats.date_pattern) + "</b></span>");
    // Counts and extremes taken from a sample are estimates, and saying so is
    // the difference between a profile and a claim.
    if (numbers.length && !sampling.exact) numbers.push('<span class="estimate">from the sample</span>');

    const rationale = unknown
      ? "<b>Left unknown.</b> " + esc(column.rationale || "The evidence did not support a guess.")
      : esc(column.rationale || "");

    return (
      '<article class="col ' + (column.user_confirmed ? "conf" : unknown ? "unk" : "") + '">' +
        '<div class="strip">' +
          '<div class="cap">sampled</div>' +
          (examples.length ? examples.map(v => '<div class="sv">' + esc(v) + "</div>").join("")
                           : '<div class="sv">(all null)</div>') +
        "</div>" +
        '<div class="col-main">' +
          '<div class="col-top">' +
            '<span class="idx">' + String(column.physical_index).padStart(2, "0") + "</span>" +
            '<span class="pname">' + esc(column.physical_name) + "</span>" +
            '<span class="pill">' + esc(column.physical_type) + "</span>" +
          "</div>" +
          '<div class="col-edit">' +
            '<div class="field"><label for="n' + column.physical_index + '">Name a query can use</label>' +
              '<input class="control sname" id="n' + column.physical_index + '" value="' +
                esc(column.semantic_name) + '"></div>' +
            '<div class="field"><label for="t' + column.physical_index + '">Meaning</label>' +
              '<select class="control stype" id="t' + column.physical_index + '">' +
                typeOptions(column.semantic_type) + "</select></div>" +
            '<div class="meterwrap"><div class="lab"><span>confidence</span><span>' +
              confidencePercent + "%</span></div>" +
              '<div class="meter' + (confidencePercent < 50 ? " low" : "") + '"><i style="width:' +
                confidencePercent + '%"></i></div>' +
              '<div class="lab"><span>' + (column.user_confirmed ? "confirmed by you" : "proposed") +
              "</span></div></div>" +
          "</div>" +
          (rationale ? '<p class="why">' + rationale + "</p>" : "") +
          (numbers.length ? '<p class="numbers">' + numbers.join("") + "</p>" : "") +
        "</div>" +
      "</article>"
    );
  }).join("");

  const ai = data.ai && data.ai.ran
    ? '<div class="panel" style="margin-top:14px">' +
        '<div class="mono tiny muted">Provider: ' + esc(data.ai.provider) + "</div>" +
        '<ul class="notes">' + (data.ai.notes || []).map(n => "<li>" + esc(n) + "</li>").join("") + "</ul>" +
        '<details class="prompt"><summary>What would be sent to a real model</summary>' +
          '<pre class="code">' + esc(data.ai.prompt || "") + "</pre></details>" +
      "</div>"
    : "";

  $("#schemaBody").innerHTML =
    facts + method +
    '<div class="cols">' + columns + "</div>" + ai +
    '<div class="row" style="margin-top:20px">' +
      '<button class="btn" id="confirmBtn">Confirm this schema</button>' +
      '<button class="btn ghost" id="skipBtn">Use it without confirming</button>' +
    "</div>";

  $("#confirmBtn").addEventListener("click", confirmSchema);
  $("#skipBtn").addEventListener("click", () => { unlock(3); go(3); });
}

async function confirmSchema(){
  const button = $("#confirmBtn");
  button.disabled = true;
  busy(true);
  try {
    const edits = $$(".col").map((node, index) => ({
      physical_index: index,
      semantic_name: $(".sname", node).value.trim(),
      semantic_type: $(".stype", node).value
    }));
    const result = await api("POST", "/api/confirm", { path: state.path, columns: edits });
    state.inspect.columns = result.columns;
    renderSchema(state.inspect);
    unlock(2, true);
    unlock(3);
    buildSuggestions();
    toast("Schema confirmed and cached beside the dataset.");
    go(3);
  } catch (error) {
    toast(error.message, true);
    button.disabled = false;
  }
  busy(false);
}

/* ------------------------------------------------------------------ ask --- */
function buildRunControls(){
  const cores = navigator.hardwareConcurrency || 8;
  const counts = [1, 2, 4, 8, 16, 32].filter(n => n <= Math.max(16, cores * 2));
  // Default to the largest count this machine can actually use. Matching the
  // core count exactly would fall through to the first option (one worker) on
  // any machine whose core count is not in the list.
  const preferred = counts.filter(n => n <= cores).pop() || counts[0];
  $("#workers").innerHTML = counts.map(n =>
    '<option value="' + n + '"' + (n === preferred ? " selected" : "") + ">" + n + "</option>").join("");
  $("#parts").innerHTML = '<option value="0">match workers</option>' +
    counts.map(n => '<option value="' + n + '">' + n + "</option>").join("");
}

function buildSuggestions(){
  const columns = (state.inspect && state.inspect.columns) || [];
  const find = t => columns.find(c => c.semantic_type === t);
  const money = find("MONETARY") || columns.find(c => c.physical_type === "DECIMAL");
  const group = find("COUNTRY") || find("CATEGORY") || find("STATUS");
  const time = find("TIMESTAMP") || find("DATE");

  const ideas = [];
  if (money && group) ideas.push("Show total " + money.semantic_name + " by " + group.semantic_name);
  if (money && group && time) ideas.push("Show total " + money.semantic_name + " by " + group.semantic_name + " in 2025");
  if (group) ideas.push("Count rows by " + group.semantic_name);
  if (money) ideas.push("What is the average " + money.semantic_name);
  if (money && group) ideas.push("Top 3 " + group.semantic_name + " by " + money.semantic_name);

  $("#suggest").innerHTML = ideas.slice(0, 4)
    .map(t => '<button class="chip" type="button">' + esc(t) + "</button>").join("");
)MEROPE_UI",
R"MEROPE_UI(  if (ideas.length) $("#q").placeholder = ideas[0];
}

$("#suggest").addEventListener("click", event => {
  const chip = event.target.closest(".chip");
  if (!chip) return;
  $("#q").value = chip.textContent;
  runQuery();
});

const STAGES = [
  ["question",  "natural language"],
  ["plan",      "JSON from the model"],
  ["validator", "columns, types, limits"],
  ["physical",  "projection and slots"],
  ["execute",   "partitioned scan"],
  ["result",    "rows and metrics"]
];

function renderChain(states){
  $("#chain").innerHTML = STAGES.map(([key, description], index) => {
    const status = states[index] || "pending";
    const label = status === "is-blocked" ? "rejected"
                : status === "is-done" ? "done"
                : status === "is-active" ? "running"
                : status === "is-skipped" ? "not reached" : "waiting";
    return '<li class="' + status + '"><span class="k"><span class="dot"></span>' + key + "</span>" +
           '<span class="v">' + esc(status === "pending" || status === "is-skipped" ? description : label) +
           "</span></li>";
  }).join("");
}

async function runQuery(){
  if (state.busy) return;
  const question = $("#q").value.trim() || $("#q").placeholder;
  if (!question || !state.path) return;
  $("#q").value = question;

  busy(true);
  $("#runBtn").disabled = true;
  $("#askOut").innerHTML = "";
  go(3);

  const states = ["is-done", "is-active", "pending", "pending", "pending", "pending"];
  renderChain(states);
  await wait(320);

  try {
    const started = performance.now();
    const request = {
      path: state.path,
      question,
      workers: Number($("#workers").value),
      partitions: Number($("#parts").value),
      policy: $("#policy").value,
      baseline: $("#baseline").value === "1",
      model: chosenModel()
    };
    // A small file would otherwise never split; honour the chosen worker count.
    request.min_partition_bytes = 1;

    const promise = api("POST", "/api/query", request);
    states[1] = "is-done"; states[2] = "is-active"; renderChain(states);
    await wait(280);

    const outcome = await promise;
    state.outcome = outcome;

    if (!outcome.accepted){
      states[2] = "is-blocked";
      states[3] = states[4] = states[5] = "is-skipped";
      renderChain(states);
      renderRejection(outcome);
      $("#runBtn").disabled = false;
      busy(false);
      return;
    }

    states[2] = "is-done"; states[3] = "is-active"; renderChain(states);
    await wait(200);
    states[3] = "is-done"; states[4] = "is-active"; renderChain(states);
    await wait(Math.min(600, Math.max(0, outcome.report.seconds * 1000 - (performance.now() - started))));
    states[4] = "is-done"; states[5] = "is-done"; renderChain(states);

    renderPlanPanels(outcome);
    renderResult(outcome);
    writeLink();
    unlock(4, true);
    go(4);
  } catch (error) {
    renderChain(["is-done","is-blocked","is-skipped","is-skipped","is-skipped","is-skipped"]);
    $("#askOut").innerHTML = '<div class="verdict stop"><h3>The engine could not run that</h3><p>' +
      esc(error.message) + "</p></div>";
    toast(error.message, true);
  }
  $("#runBtn").disabled = false;
  busy(false);
}

$("#runBtn").addEventListener("click", runQuery);
$("#q").addEventListener("keydown", event => { if (event.key === "Enter") runQuery(); });

function warningsBlock(outcome){
  if (!outcome.warnings || !outcome.warnings.length) return "";
  return '<div class="verdict warn"><h3>The canonicaliser changed the plan</h3><ul>' +
    outcome.warnings.map(w => "<li>" + esc(w) + "</li>").join("") + "</ul></div>";
}

function renderRejection(outcome){
  $("#askOut").innerHTML =
    '<div class="verdict stop">' +
      "<h3>Plan rejected</h3><ul>" +
      (outcome.errors || []).map(e => "<li>" + esc(e) + "</li>").join("") +
      "</ul><p>Nothing was executed. The plan never reached the engine.</p></div>" +
    warningsBlock(outcome) +
    '<div class="split" style="margin-top:14px">' +
      '<div class="panel"><h2 style="margin-top:0">What the model returned</h2>' +
        '<pre class="code">' + esc(JSON.stringify(outcome.logical_plan, null, 2)) + "</pre></div>" +
      '<div class="panel"><h2 style="margin-top:0">Reading of it</h2>' +
        '<pre class="code">' + esc(outcome.plan_text || "") + "</pre></div>" +
    "</div>";
}

function renderPlanPanels(outcome){
  $("#askOut").innerHTML = warningsBlock(outcome) +
    '<div class="split" style="margin-top:14px">' +
      '<div class="panel"><h2 style="margin-top:0">Plan from the model</h2>' +
        '<pre class="code">' + esc(JSON.stringify(outcome.logical_plan, null, 2)) + "</pre></div>" +
      '<div class="panel"><h2 style="margin-top:0">What the engine will do</h2>' +
        '<pre class="code">' + esc(outcome.physical_plan || "") + "</pre></div>" +
    "</div>";
}

/* --------------------------------------------------------------- result --- */
function isNumericType(t){ return t === "INT64" || t === "FLOAT64" || t === "DECIMAL"; }

function renderResult(outcome){
  const report = outcome.report;
  const tiles = [
    ["Records read", fmtInt(report.records), ""],
    ["Time", report.seconds.toFixed(2), "s"],
    ["Throughput", report.throughput_mb_s.toFixed(0), "MB/s"],
    ["Peak memory", report.peak_memory, ""],
    ["Workers", fmtInt(report.workers), ""],
    ["Partitions", fmtInt(report.partitions), ""]
  ];
  if (report.rows_after_filter !== report.records) {
    tiles.splice(1, 0, ["After filter", fmtInt(report.rows_after_filter), ""]);
  }
  if (report.groups) tiles.push(["Groups", fmtInt(report.groups), ""]);
  if (report.bad_rows) tiles.push(["Broken rows", fmtInt(report.bad_rows), report.bad_row_policy]);
  if (report.has_baseline) {
    tiles.push(["Single threaded", report.baseline_seconds.toFixed(2), "s"]);
    tiles.push(["Speedup", report.speedup.toFixed(2), "x"]);
  }

  const tileHtml = '<dl class="tiles">' + tiles.map(([label, value, unit], index) =>
    '<div class="tile' + (index === 0 ? " hero" : "") + '"><dt>' + esc(label) + "</dt><dd>" +
    esc(value) + (unit ? "<small>" + esc(unit) + "</small>" : "") + "</dd></div>").join("") + "</dl>";

  const notes = [];
  if (outcome.limited) notes.push("The result was cut off by the plan limit.");
  if (outcome.result_warning) notes.push(outcome.result_warning);
  if (report.partition_note) notes.push(report.partition_note);
  const noteHtml = notes.length
    ? '<ul class="notes" style="margin-top:12px">' + notes.map(n => "<li>" + esc(n) + "</li>").join("") + "</ul>"
    : "";

  const head = "<thead><tr>" + outcome.columns.map((c, i) =>
    "<th>" + esc(c) + '<span class="t">' + esc(outcome.types[i] || "") + "</span></th>").join("") + "</tr></thead>";
  const body = "<tbody>" + outcome.rows.map(row => "<tr>" + row.map((cell, i) =>
    '<td class="' + (isNumericType(outcome.types[i]) ? "num" : "") + '">' + esc(cell) + "</td>").join("") +
    "</tr>").join("") + "</tbody>";

  $("#resultBody").innerHTML =
    tileHtml + noteHtml +
    '<div id="chartHost"></div>' +
    "<h2>" + fmtInt(outcome.rows.length) + " row" + (outcome.rows.length === 1 ? "" : "s") + "</h2>" +
    '<div class="tablewrap"><table>' + head + body + "</table></div>" +
    '<div class="row" style="margin-top:20px">' +
      '<button class="btn ghost" id="againBtn">Ask something else</button></div>';

  $("#againBtn").addEventListener("click", () => { go(3); $("#q").select(); });
  renderChart(outcome);
}

/* A horizontal bar chart: the data's job here is magnitude by category, and the
   values share one scale, so one measure gets one axis and one hue whose
   lightness tracks the value. Identity is carried by the labels, not by colour. */
function renderChart(outcome){
  const host = $("#chartHost");
  host.innerHTML = "";
  const types = outcome.types || [];

  let valueIndex = -1;
  for (let i = 0; i < types.length; i++){
    if (isNumericType(types[i]) && outcome.numeric.some(r => r[i] != null)) { valueIndex = i; break; }
  }
  if (valueIndex < 0) return;
  let labelIndex = types.findIndex((t, i) => i !== valueIndex && !isNumericType(t));
  if (labelIndex < 0) labelIndex = types.findIndex((t, i) => i !== valueIndex);
  if (labelIndex < 0) return;

  const points = outcome.rows.map((row, r) => ({
    label: row[labelIndex],
    display: row[valueIndex],
    value: outcome.numeric[r][valueIndex]
  })).filter(p => p.value != null);

  if (points.length < 2) return;
  const shown = points.slice(0, 24);
  const max = Math.max(...shown.map(p => Math.abs(p.value)));
  if (!(max > 0)) return;

  const longest = shown.reduce((n, p) => Math.max(n, String(p.label).slice(0, 18).length), 2);
  const rowHeight = 26, barHeight = 13, right = 66, top = 26;
  const gutter = Math.min(190, Math.max(46, longest * 7 + 14));
  const width = 760;
  const height = top + shown.length * rowHeight + 8;
  const plot = width - gutter - right;
  const labelAll = shown.length <= 14;
  // Every bar carries its own value when the list is short, so the axis would
  // just be a second copy of the same numbers. Keep the grid, drop the labels.
  const ticks = [0, 0.25, 0.5, 0.75, 1];

  const parts = [];
  parts.push('<svg viewBox="0 0 ' + width + " " + height + '" role="img" aria-label="' +
             esc(outcome.columns[valueIndex]) + " by " + esc(outcome.columns[labelIndex]) + '">');

  ticks.forEach(t => {
    const x = gutter + plot * t;
    parts.push('<line class="grid" x1="' + x + '" y1="' + (top - 8) + '" x2="' + x +
               '" y2="' + (height - 8) + '"/>');
    if (!labelAll){
      parts.push('<text class="axis" x="' + x + '" y="' + (top - 14) + '" text-anchor="middle">' +
                 esc(fmtCompact(max * t)) + "</text>");
    }
  });

  shown.forEach((point, index) => {
    const y = top + index * rowHeight;
    const ratio = Math.abs(point.value) / max;
    const barWidth = Math.max(2, plot * ratio);
    // One series, one colour. Bar length already encodes magnitude, so tinting
    // by value would be a second copy of the same information.
    parts.push('<g class="mark" tabindex="0" data-label="' + esc(point.label) +
               '" data-value="' + esc(point.display) + '">');
    parts.push('<text class="cat" x="' + (gutter - 12) + '" y="' + (y + barHeight - 2) +
               '" text-anchor="end">' + esc(String(point.label).slice(0, 18)) + "</text>");
    parts.push('<path class="bar" d="' + barPath(gutter, y, barWidth, barHeight, 4) +
               '" fill="#8b5cf6"/>');
    if (labelAll){
      parts.push('<text class="val" x="' + (gutter + barWidth + 9) + '" y="' + (y + barHeight - 2) +
                 '">' + esc(fmtCompact(point.value)) + "</text>");
    }
    parts.push("</g>");
  });
  parts.push("</svg>");

  const caption = esc(outcome.columns[valueIndex]) + " by " + esc(outcome.columns[labelIndex]) +
    (points.length > shown.length ? " · showing the first " + shown.length + " of " + points.length : "");

)MEROPE_UI",
R"MEROPE_UI(  host.innerHTML = '<figure class="chart panel" style="margin-top:14px">' +
    "<figcaption>" + caption + "</figcaption>" + parts.join("") + "</figure>";

  $$(".mark", host).forEach(mark => {
    const show = event => {
      const tip = $("#tip");
      tip.innerHTML = "<b>" + esc(mark.dataset.label) + "</b><span>" +
        esc(outcome.columns[valueIndex]) + ": " + esc(mark.dataset.value) + "</span>";
      const box = mark.getBoundingClientRect();
      const x = event.clientX != null ? event.clientX : box.right;
      const y = event.clientY != null ? event.clientY : box.top;
      tip.style.left = Math.min(window.innerWidth - 290, x + 14) + "px";
      tip.style.top = (y - 8) + "px";
      tip.classList.add("on");
    };
    mark.addEventListener("mouseenter", show);
    mark.addEventListener("mousemove", show);
    mark.addEventListener("focus", show);
    const hide = () => $("#tip").classList.remove("on");
    mark.addEventListener("mouseleave", hide);
    mark.addEventListener("blur", hide);
  });
}

// Square against the baseline, rounded at the data end.
function barPath(x, y, w, h, r){
  const radius = Math.min(r, w, h / 2);
  return "M" + x + "," + y +
         " H" + (x + w - radius) +
         " A" + radius + "," + radius + " 0 0 1 " + (x + w) + "," + (y + radius) +
         " V" + (y + h - radius) +
         " A" + radius + "," + radius + " 0 0 1 " + (x + w - radius) + "," + (y + h) +
         " H" + x + " Z";
}

buildSky();
animateSky();
scheduleMeteors();
boot();
</script>
</body>
</html>)MEROPE_UI",
};

// The whole application in one document, served from memory. No external font,
// script or stylesheet is fetched, so the UI works with no network at all.
std::string_view merope::ui_document() {
    static const std::string document = [] {
        std::string joined;
        std::size_t total = 0;
        for (const std::string_view part : k_parts) total += part.size();
        joined.reserve(total);
        for (const std::string_view part : k_parts) joined.append(part);
        return joined;
    }();
    return document;
}