# tools/embed_ui.ps1 - regenerates merope/src/web/ui_assets.cpp from ui.html.
#
# The UI is authored as a normal HTML file and embedded in the binary so the
# executable stays self contained. MSVC caps a single string literal at 16 KB,
# so the document is emitted as chunks that are joined once at runtime.
#
# Run this after editing merope/src/web/ui.html:
#   powershell -ExecutionPolicy Bypass -File tools\embed_ui.ps1

$ErrorActionPreference = "Stop"

$root   = Split-Path -Parent $PSScriptRoot
$source = Join-Path $root "merope\src\web\ui.html"
$target = Join-Path $root "merope\src\web\ui_assets.cpp"

if (-not (Test-Path $source)) { throw "missing $source" }

$utf8  = New-Object System.Text.UTF8Encoding($false)
$text  = [System.IO.File]::ReadAllText($source, [System.Text.Encoding]::UTF8)

if ($text.Contains(')MEROPE_UI"')) {
    throw "ui.html contains the raw string terminator; pick a different delimiter"
}

# Split on line boundaries, keeping each chunk well under the 16 KB literal cap.
$lines  = $text -split "(?<=\n)"
$chunks = New-Object System.Collections.ArrayList
$buffer = New-Object System.Text.StringBuilder
$bytes  = 0
foreach ($line in $lines) {
    $size = [System.Text.Encoding]::UTF8.GetByteCount($line)
    if ($bytes -gt 0 -and ($bytes + $size) -gt 11000) {
        [void]$chunks.Add($buffer.ToString())
        $buffer = New-Object System.Text.StringBuilder
        $bytes  = 0
    }
    [void]$buffer.Append($line)
    $bytes += $size
}
if ($buffer.Length -gt 0) { [void]$chunks.Add($buffer.ToString()) }

$out = New-Object System.Text.StringBuilder
[void]$out.Append(@'
// Generated by tools/embed_ui.ps1 from merope/src/web/ui.html - do not edit.
#include "ui_assets.h"

#include <string>

// The document is held in pieces purely because MSVC caps a single string
// literal at 16 KB. They are joined once, on first use.
static constexpr std::string_view k_parts[] = {
'@)
[void]$out.Append("`n")
foreach ($chunk in $chunks) {
    [void]$out.Append('R"MEROPE_UI(')
    [void]$out.Append($chunk)
    [void]$out.Append(')MEROPE_UI",')
    [void]$out.Append("`n")
}
[void]$out.Append(@'
};

// The whole application in one document, served from memory. No external font,
// script or stylesheet is fetched, so the UI works with no network at all.
std::string_view merope::ui_document() {
    static const std::string document = [] {
        std::string joined;
        std::size_t total = 0;
        for (const std::string_view part : k_parts) total += part.size();
        joined.reserve(total);
        for (const std::string_view part : k_parts) joined.append(part);
        return joined;
    }();
    return document;
}
'@)

[System.IO.File]::WriteAllText($target, $out.ToString(), $utf8)
Write-Host ("embedded {0} bytes as {1} chunks into {2}" -f
            [System.Text.Encoding]::UTF8.GetByteCount($text), $chunks.Count, $target)
